apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nlp-para-summarize
  name: nlp-para-summarize-service
spec:
  ports:
    - name: "32310"
      port: 32310
      targetPort: 8000
  selector:
    io.kompose.service: nlp-para-summarize
